#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Wait one second for messages to stop
sleep 1


# pint welcome message
cat <<!



Welcome to Minibox shell



!


# cttyhack is to make sh figure out which 
# tty the console is coming from automatically
setsid cttyhack sh

